# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

MAX_VALUE = 4_000_000

def sum_of_even_fibonacci
  sum = 0

  (0..256).each do |n|
    f = fib(n)
    if f < MAX_VALUE && f.even?
      sum += f
    end
  end

  return sum
end

# Helpers

def fib(n)
  fib_r(1, 2, n)
end

# where a, b are the seeds
# and n is the sequence
def fib_r(a, b, n)
  n == 0 ? a : fib_r(b, a + b, n - 1)
end
